stages:
  data_ingestion:
    cmd:
    - python3 src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw
  data_preprocess:
    cmd:
    - python3 src/data_preprocess.py
    deps:
    - data/raw
    - src/data_preprocess.py
    outs:
    - data/interim
  feature_eng:
    cmd:
    - python3 src/feature_eng.py
    deps:
    - data/interim
    - src/feature_eng.py
    outs:
    - data/processed
  model_building:
    cmd:
    - python3 src/model_building.py
    deps:
    - data/processed
    - src/model_building.py
    outs:
    - models/model.pkl
  model_evaluation:
    cmd:
    - python3 src/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model_evaluation.py
    outs:
    - reports/metrics.json
  
